### PR TITLE
webhook: initial implementation

### LINKED ISSUE #4: Update states of devices
Use web-sockets to fetch data and refresh state of all devices

### PR DESCRIPTION
**Pull request by stanleyyyy**
This commmit adds support for Webhooks (remote triggers from Taphome to force update of the whole Taphome context)
Webhooks can be used instead of continuous polling of Taphome API to reduce the amount of unnecessary HTTP traffic exchanged between this integration and Taphome.

How to use it:
1) add 'webhook_url' property key to taphome integration configuration area in configurations.yaml.
The value of this property specifies the Webhook URL, which may be called from outside to initiate Taphome integration refresh.
If the 'webhook_url' property is not specified, webhook feature will be disabled.

2) enable webhooks in Taphome configuration (Settings/Expose Devices/TapHome API/Enable Web Hook) and set
Web Hook URL to the following format:

http://<home_assistant_ip_address>:8123/api/webhook/<webhook_url>

where '<home_assistant_ip>' is the IP address of your home assistant instance and '<webhook_url>' is the URL
you specified in configurations.yaml

3) increase the value of 'update_interval' to some large number as it is no longer necessary

Signed-off-by: Stanislav Ruzani <stanislav.ruzani@gmail.com>

### CODE REVIEW

**Comment by martindybal** [comment]
Maybe we should disable polling http completely when webhooks is set. How reliable are webhooks?  Is it better to refresh data once a minute just in case?

**Comment by stanleyyyy** [comment]
> Maybe we should disable polling http completely when webhooks is set. How reliable are webhooks? Is it better to refresh data once a minute just in case?

It seems to be quite reliable, I am running it for the whole day and this far I haven't see any problems.
But I have a few reasons why we might still need the polling:
1) the latency:
The current webhook latency is quite high, 1.5-2 seconds on my setup. That means that if you really need super low latency, it is still better to use fast 1 second explicit polling. I believe this will for sure be improved by Taphome in the future, but at this moment a webhook is slightly slower alternative
2) the configuration simplicity:
In order to use webhooks, the users have to explicitly configure this feature in Taphome App. They need to set the ip address of HA server, the webhook URL etc. It is not difficult, but it is just one more aditional step which could be a "problem" for some users.
3) might not work if HomeAssistant server is located on a different network than Taphome
Webhook call of course has to access the HomeAssistant server directly. In case these are located on different networks, where direct connectivity is not possible, the users have to still use polling. This includes most installations where this integration is running via remote API. Of course this could be solved using IFTTT webhooks, but it again adds aditional complexity.

So I believe we should still keep the polling feature in, at least for now...

**Comment by polcape** [comment]
I test webhook feature from this morning and seems works fine, except the delay of 1/2 sec as @stanleyyyy wrote.

I agree to keep the polling mode in the integration for the reason above.

**Comment by martindybal** [comment]
There some miss understanding. I don't want to remove polling completely. Just disable it when webhook is configured.

**Comment by stanleyyyy** [comment]
> There some miss understanding. I don't want to remove polling completely. Just disable it when webhook is configured.

Ah OK, in this case I think you can safely remove it when webhooks are enabled.. In worst case everyone can just revert back to polling mode.

**Pull request merged**
