### PR TITLE
Add few sensors

### PR DESCRIPTION
**Pull request by polcape**

### CODE REVIEW

**Comment by martindybal** [comment]
I check the code, I don't test functionality. It looks good for me with few comments. You should also update readme and changelog.

**Comment by polcape** [comment]
@martindybal what comments should I add?

**Comment by martindybal** [comment]
@polcape I merged it to my feature branch for easier development. But all my comments here is still relevant. 

1. We can use test string directly. We have to use translations like other integrations
2. We should implement Brightness sensor as `illuminance` #48 
3. Update readme and changelog
4. Check how real rain sensor works. Because virtual one return sum of precipitation from whole his history. We need precipitation in mm/h and maybe also binary sensor it's rain or not

**Comment by polcape** [comment]
Ok, thanks for suggestion.
>     1. We can't use text string directly. We have to use translations like other integrations
What do you mean with this sentence? I don't understand.

>     2. We should implement Brightness sensor as `illuminance` device class #48
I proposed here a proportion https://github.com/martindybal/taphome-homeassistant/issues/48

>     3. Update readme and changelog
Done with https://github.com/martindybal/taphome-homeassistant/commit/802c419a0282a387f312a2593a8d58723babac01

>     4. Check how real rain sensor works. Because virtual returns sum of precipitation from whole his history. We need precipitation in mm/h and maybe also binary sensor it's rain or not
I use virtual rain counter, that have mm, But now I see rain sensors working is explained here https://taphome.com/en/support/342392892
Seems to be done in different ways, based on smart rule, in the example show mm/48h, that is not a standard value for HA. Ho we implement it?

**Comment by martindybal** [comment]
1. You can't use "total" we have used translations like this https://github.com/home-assistant/core/tree/dev/homeassistant/components/hue/translations
2. agree
3. good
4. HA has `PRECIPITATION_MILLIMETERS_PER_HOUR = "mm/h"`. We can calculate this. But I don't like it. I'll ask TapHome team for help. It can be good on their app too. For now we can remove `TapHomeRainCounterSensor`what so you think?

**Comment by polcape** [comment]
>     1. You can't use "total" we have used translations like this https://github.com/home-assistant/core/tree/dev/homeassistant/components/hue/translations
Interesting. I don't undestand perfectly how works, but yes. We have to do like Hue.
I have introduced the two string "total" and "current hour" because there isn't unit of measurement to discriminate the two entity (like temperature and humidity for the thermostat, they have same name but different units)

>     4. HA has `PRECIPITATION_MILLIMETERS_PER_HOUR = "mm/h"`. We can calculate this. But I don't like it. I'll ask TapHome team for help. It can be good on their app too. For now we can remove `TapHomeRainCounterSensor`what so you think?
Yes, I agree! mm/h should be the base unit. And from it the user can change as he want (also in TapHome App). I will delete RainCounter

**Comment by martindybal** [comment]
1. https://developers.home-assistant.io/docs/internationalization/custom_integration/

**Pull request merged**
